### ISSUE TITLE
Question: failed to cross compile ring

### ISSUE THREAD

**Issue by smw-wagnerma** [jamesmcm/rust_ses_example#1]
Thanks for your blog post!
I am working on a lambda function sending a mail over smtp using the same libs like you. I use cross to compile to the musl target. Locally all is fine, but running the build on a github action I struggle. Perhaps you have any ideas? I also tried to use openSSL, but the errors are even worser ;-(
The error:

```
cross build --target x86_64-unknown-linux-musl --release

info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.47.0 (18bf6b4f0 2020-10-07)

info: checking for self-updates
info: downloading component 'rust-src'
info: installing component 'rust-src'
info: Defaulting to 500.0 MiB unpack ram
Unable to find image 'lambci/lambda:build-provided' locally
build-provided: Pulling from lambci/lambda
f9fc003cec10: Pulling fs layer
9f0ae58b25e8: Pulling fs layer
8ef6b2d792e1: Pulling fs layer
f2ed6ee74967: Pulling fs layer
d7024d736b4a: Pulling fs layer
b4fff841a613: Pulling fs layer
f2ed6ee74967: Waiting
d7024d736b4a: Waiting
b4fff841a613: Waiting
8ef6b2d792e1: Verifying Checksum
8ef6b2d792e1: Download complete
f2ed6ee74967: Verifying Checksum
f2ed6ee74967: Download complete
d7024d736b4a: Verifying Checksum
d7024d736b4a: Download complete
b4fff841a613: Verifying Checksum
b4fff841a613: Download complete
f9fc003cec10: Verifying Checksum
f9fc003cec10: Download complete
9f0ae58b25e8: Verifying Checksum
9f0ae58b25e8: Download complete
f9fc003cec10: Pull complete
9f0ae58b25e8: Pull complete
8ef6b2d792e1: Pull complete
f2ed6ee74967: Pull complete
d7024d736b4a: Pull complete
b4fff841a613: Pull complete
Digest: sha256:ec832dcb55475803d6b08beba87ad0922ac39ef9e4248e4a3fab0eafe4de3c7e
Status: Downloaded newer image for lambci/lambda:build-provided
    Updating git repository `https://github.com/awslabs/aws-lambda-rust-runtime`
 Downloading crates ...
  Downloaded matches v0.1.8
  Downloaded fake-simd v0.1.2
  Downloaded base64 v0.11.0
  Downloaded rand_core v0.5.1
  Downloaded pin-project v0.4.27
  Downloaded tracing-attributes v0.1.11
  Downloaded try-lock v0.2.3
  Downloaded tracing-futures v0.2.4
  Downloaded webpki v0.21.3
  Downloaded unicode-bidi v0.3.4
  Downloaded untrusted v0.7.1
  Downloaded http-body v0.3.1
  Downloaded want v0.3.0
  Downloaded zeroize v1.1.1
  Downloaded url v2.1.1
  Downloaded tracing v0.1.21
  Downloaded dirs v2.0.2
  Downloaded tracing-error v0.1.2
  Downloaded dtoa v0.4.6
  Downloaded webpki-roots v0.20.0
  Downloaded sharded-slab v0.1.0
  Downloaded spin v0.5.2
  Downloaded iovec v0.1.4
  Downloaded tower-service v0.3.0
  Downloaded thread_local v1.0.1
  Downloaded quote v1.0.7
  Downloaded pin-project-internal v0.4.27
  Downloaded once_cell v1.4.1
  Downloaded pin-project-internal v1.0.1
  Downloaded pin-project v1.0.1
  Downloaded base64 v0.12.3
  Downloaded mio v0.6.22
  Downloaded percent-encoding v2.1.0
  Downloaded futures-sink v0.3.7
  Downloaded socket2 v0.3.15
  Downloaded unicode-normalization v0.1.13
  Downloaded fnv v1.0.7
  Downloaded rusoto_s3 v0.44.0
  Downloaded tracing-subscriber v0.2.14
  Downloaded lettre v0.10.0-alpha.3
  Downloaded hyperx v1.2.0
  Downloaded pin-project-lite v0.1.11
  Downloaded signal-hook-registry v1.2.1
  Downloaded shlex v0.1.1
  Downloaded h2 v0.2.7
  Downloaded hyper v0.13.8
  Downloaded chrono v0.4.19
  Downloaded rustls v0.18.1
  Downloaded syn v1.0.45
  Downloaded rustls v0.17.0
  Downloaded libc v0.2.79
  Downloaded openssl-probe v0.1.2
  Downloaded num_cpus v1.13.0
  Downloaded regex v1.4.1
  Downloaded futures-io v0.3.7
  Downloaded ring v0.16.15
  Downloaded regex-syntax v0.6.20
  Downloaded log v0.4.11
  Downloaded lexical-core v0.7.4
  Downloaded hashbrown v0.9.1
  Downloaded async-trait v0.1.41
  Downloaded tokio v0.2.22
  Downloaded standback v0.2.11
  Downloaded mio-uds v0.6.8
  Downloaded md5 v0.7.0
  Downloaded futures-channel v0.3.7
  Downloaded async-stream v0.2.1
  Downloaded rusoto_core v0.44.0
  Downloaded proc-macro2 v0.4.30
  Downloaded proc-macro-hack v0.5.18
  Downloaded ppv-lite86 v0.2.9
  Downloaded idna v0.2.0
  Downloaded opaque-debug v0.2.3
  Downloaded mime v0.3.16
  Downloaded dirs-sys v0.3.5
  Downloaded block-padding v0.1.5
  Downloaded base64 v0.13.0
  Downloaded aho-corasick v0.7.14
  Downloaded static_assertions v1.1.0
  Downloaded sct v0.6.0
  Downloaded language-tags v0.2.2
  Downloaded byteorder v1.3.4
  Downloaded arc-swap v0.4.7
  Downloaded indexmap v1.6.0
  Downloaded cc v1.0.61
  Downloaded bytes v0.5.6
  Downloaded httparse v1.3.4
  Downloaded xml-rs v0.8.3
  Downloaded serde_derive v1.0.117
  Downloaded httpdate v0.3.2
  Downloaded futures-executor v0.3.7
  Downloaded futures-core v0.3.7
  Downloaded unicode-xid v0.2.1
  Downloaded time v0.1.44
  Downloaded http v0.2.1
  Downloaded futures-util v0.3.7
  Downloaded futures-task v0.3.7
  Downloaded const_fn v0.4.2
  Downloaded typenum v1.12.0
  Downloaded tracing-core v0.1.17
  Downloaded memchr v2.3.3
  Downloaded tokio-util v0.3.1
  Downloaded proc-macro2 v1.0.24
  Downloaded proc-macro-nested v0.1.6
  Downloaded hmac v0.7.1
  Downloaded getrandom v0.1.15
  Downloaded generic-array v0.12.3
  Downloaded digest v0.8.1
  Downloaded ct-logs v0.6.0
  Downloaded crypto-mac v0.7.0
  Downloaded colored v1.9.3
  Downloaded byte-tools v0.3.1
  Downloaded block-buffer v0.7.3
  Downloaded async-stream-impl v0.2.1
  Downloaded uuid v0.8.1
  Downloaded unicode-xid v0.1.0
  Downloaded unicase v2.6.0
  Downloaded subtle v1.0.0
  Downloaded simple_logger v1.11.0
  Downloaded sha2 v0.8.2
  Downloaded rusoto_credential v0.44.0
  Downloaded serde_urlencoded v0.6.1
  Downloaded rusoto_signature v0.44.0
  Downloaded rand_chacha v0.2.2
  Downloaded quoted_printable v0.4.2
  Downloaded slab v0.4.2
  Downloaded rand v0.7.3
  Downloaded nom v5.1.2
  Downloaded tokio-rustls v0.13.1
  Downloaded tokio-macros v0.2.5
  Downloaded tinyvec v0.3.4
  Downloaded time-macros-impl v0.1.1
  Downloaded time-macros v0.1.1
  Downloaded time v0.2.22
  Downloaded rustls-native-certs v0.3.0
  Downloaded num-traits v0.2.12
  Downloaded hyper-rustls v0.20.0
  Downloaded num-integer v0.1.43
  Downloaded net2 v0.2.35
  Downloaded futures v0.3.7
  Downloaded pin-utils v0.1.0
  Downloaded hex v0.4.2
  Downloaded futures-macro v0.3.7
  Downloaded arrayvec v0.5.2
   Compiling libc v0.2.79
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.45
   Compiling cfg-if v0.1.10
   Compiling log v0.4.11
   Compiling lazy_static v1.4.0
   Compiling once_cell v1.4.1
   Compiling version_check v0.9.2
   Compiling memchr v2.3.3
   Compiling autocfg v1.0.1
   Compiling slab v0.4.2
   Compiling futures-core v0.3.7
   Compiling bytes v0.5.6
   Compiling fnv v1.0.7
   Compiling proc-macro-hack v0.5.18
   Compiling itoa v0.4.6
   Compiling pin-project-lite v0.1.11
   Compiling cc v1.0.61
   Compiling futures-sink v0.3.7
   Compiling proc-macro-nested v0.1.6
   Compiling spin v0.5.2
   Compiling arc-swap v0.4.7
   Compiling pin-project-internal v0.4.27
   Compiling serde_derive v1.0.117
   Compiling untrusted v0.7.1
   Compiling serde v1.0.117
   Compiling httparse v1.3.4
   Compiling ryu v1.0.5
   Compiling futures-io v0.3.7
   Compiling pin-utils v0.1.0
   Compiling typenum v1.12.0
   Compiling hashbrown v0.9.1
   Compiling httpdate v0.3.2
   Compiling try-lock v0.2.3
   Compiling tower-service v0.3.0
   Compiling serde_json v1.0.59
   Compiling percent-encoding v2.1.0
   Compiling getrandom v0.1.15
   Compiling byteorder v1.3.4
   Compiling base64 v0.11.0
   Compiling regex-syntax v0.6.20
   Compiling tinyvec v0.3.4
   Compiling matches v0.1.8
   Compiling const_fn v0.4.2
   Compiling byte-tools v0.3.1
   Compiling semver-parser v0.7.0
   Compiling base64 v0.12.3
   Compiling proc-macro2 v0.4.30
   Compiling bitflags v1.2.1
   Compiling subtle v1.0.0
   Compiling zeroize v1.1.1
   Compiling opaque-debug v0.2.3
   Compiling lexical-core v0.7.4
   Compiling openssl-probe v0.1.2
   Compiling unicode-xid v0.1.0
   Compiling fake-simd v0.1.2
   Compiling shlex v0.1.1
   Compiling ppv-lite86 v0.2.9
   Compiling static_assertions v1.1.0
   Compiling hex v0.4.2
   Compiling arrayvec v0.5.2
   Compiling md5 v0.7.0
   Compiling hyperx v1.2.0
   Compiling dtoa v0.4.6
   Compiling mime v0.3.16
   Compiling xml-rs v0.8.3
   Compiling base64 v0.13.0
   Compiling language-tags v0.2.2
   Compiling quoted_printable v0.4.2
   Compiling tracing-core v0.1.17
   Compiling thread_local v1.0.1
   Compiling sharded-slab v0.1.0
   Compiling futures-task v0.3.7
   Compiling standback v0.2.11
   Compiling time v0.2.22
   Compiling unicase v2.6.0
   Compiling nom v5.1.2
   Compiling indexmap v1.6.0
   Compiling num-traits v0.2.12
   Compiling num-integer v0.1.43
   Compiling http v0.2.1
   Compiling futures-channel v0.3.7
   Compiling ring v0.16.15
   Compiling unicode-normalization v0.1.13
   Compiling unicode-bidi v0.3.4
   Compiling block-padding v0.1.5
   Compiling semver v0.9.0
   Compiling tracing-subscriber v0.2.14
error: failed to run custom build command for `ring v0.16.15`
Error: failed to run custom build command for `ring v0.16.15`
Caused by:
  process didn't exit successfully: `/target/release/build/ring-afa95447152d292d/build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-musl")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-musl = None
  CC_x86_64_unknown_linux_musl = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_x86_64-unknown-linux-musl = None
  CFLAGS_x86_64_unknown_linux_musl = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")

  --- stderr
  ENV AWS_XRAY_CONTEXT_MISSING=LOG_ERROR
  ENV AWS_XRAY_DAEMON_ADDRESS=169.254.79.2:2000
  ENV CARGO=/rust/bin/cargo
  ENV CARGO_CFG_TARGET_ARCH=x86_64
  ENV CARGO_CFG_TARGET_ENDIAN=little
  ENV CARGO_CFG_TARGET_ENV=musl
  ENV CARGO_CFG_TARGET_FAMILY=unix
  ENV CARGO_CFG_TARGET_FEATURE=fxsr,sse,sse2
  ENV CARGO_CFG_TARGET_OS=linux
  ENV CARGO_CFG_TARGET_POINTER_WIDTH=64
  ENV CARGO_CFG_TARGET_VENDOR=unknown
  ENV CARGO_CFG_UNIX=
  ENV CARGO_FEATURE_ALLOC=1
  ENV CARGO_FEATURE_DEFAULT=1
  ENV CARGO_FEATURE_DEV_URANDOM_FALLBACK=1
  ENV CARGO_FEATURE_ONCE_CELL=1
  ENV CARGO_HOME=/cargo
  ENV CARGO_MAKEFLAGS=--jobserver-fds=6,11 -j --jobserver-auth=6,11 -j
  ENV CARGO_MANIFEST_DIR=/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15
  ENV CARGO_MANIFEST_LINKS=ring-asm
  ENV CARGO_PKG_AUTHORS=Brian Smith <brian@briansmith.org>
  ENV CARGO_PKG_DESCRIPTION=Safe, fast, small crypto using Rust.
  ENV CARGO_PKG_HOMEPAGE=
  ENV CARGO_PKG_LICENSE=
  ENV CARGO_PKG_LICENSE_FILE=LICENSE
  ENV CARGO_PKG_NAME=ring
  ENV CARGO_PKG_REPOSITORY=https://github.com/briansmith/ring
  ENV CARGO_PKG_VERSION=0.16.15
  ENV CARGO_PKG_VERSION_MAJOR=0
  ENV CARGO_PKG_VERSION_MINOR=16
  ENV CARGO_PKG_VERSION_PATCH=15
  ENV CARGO_PKG_VERSION_PRE=
  ENV CARGO_TARGET_DIR=/target
  ENV CROSS_RUNNER=
  ENV DEBUG=false
  ENV HOME=/
  ENV HOST=x86_64-unknown-linux-gnu
  ENV HOSTNAME=629711a52cf1
  ENV LAMBDA_RUNTIME_DIR=/var/runtime
  ENV LAMBDA_TASK_ROOT=/var/task
  ENV LANG=en_US.UTF-8
  ENV LD_LIBRARY_PATH=/target/release/deps:/target/release:/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
  ENV NUM_JOBS=2
  ENV OPT_LEVEL=3
  ENV OUT_DIR=/target/x86_64-unknown-linux-musl/release/build/ring-be97eb2a077ea07c/out
  ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/rust/bin
  ENV PIPX_BIN_DIR=/usr/local/bin
  ENV PIPX_HOME=/usr/local/pipx
  ENV PKG_CONFIG_ALLOW_CROSS=1
  ENV PROFILE=release
  ENV PWD=/project
  ENV RUSTC=rustc
  ENV RUSTDOC=rustdoc
  ENV SHLVL=1
  ENV SSL_CERT_DIR=/etc/pki/tls/certs
  ENV SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
  ENV TARGET=x86_64-unknown-linux-musl
  ENV TZ=:UTC
  ENV USER=runner
  ENV XARGO_HOME=/xargo
  ENV _=/rust/bin/cargo
  ENV _AWS_XRAY_DAEMON_ADDRESS=169.254.79.2
  ENV _AWS_XRAY_DAEMON_PORT=2000
  ENV _LAMBDA_CONSOLE_SOCKET=16
  ENV _LAMBDA_CONTROL_SOCKET=14
  ENV _LAMBDA_LOG_FD=9
  ENV _LAMBDA_RUNTIME_LOAD_TIME=1530232235231
  ENV _LAMBDA_SB_ID=7
  ENV _LAMBDA_SHARED_MEM_FD=11
  ENV _X_AMZN_TRACE_ID=Root=1-dc99d00f-c079a84d433534434534ef0d;Parent=91ed514f1e5c03b2;Sampled=1
  running "musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-U_FORTIFY_SOURCE" "-DNDEBUG" "-c" "-o/target/x86_64-unknown-linux-musl/release/build/ring-be97eb2a077ea07c/out/aesni-x86_64-elf.o" "/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesni-x86_64-elf.S"
  thread 'main' panicked at 'failed to execute ["musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-U_FORTIFY_SOURCE" "-DNDEBUG" "-c" "-o/target/x86_64-unknown-linux-musl/release/build/ring-be97eb2a077ea07c/out/aesni-x86_64-elf.o" "/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesni-x86_64-elf.S"]: No such file or directory (os error 2)', /cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/build.rs:661:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Warning: error: build failed
Error: The process 'cross' failed with exit code 101
```
My github action build.yml:

```
name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - run: |
          sudo apt-get install musl-tools
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-musl --release
      - run: |
          zip -r9 -j ./target/x86_64-unknown-linux-musl/release/bootstrap.zip ./target/x86_64-unknown-linux-musl/release/bootstrap

```

**Comment by jamesmcm** [comment]
It looks like you need to install musl-gcc : https://github.com/briansmith/ring/issues/563

And ensure that it is used by the build system.

It should be installed by `musl-tools` there though, maybe check it is on the path (add some debugging steps before, trying to run musl-gcc alone for example)?

I had exactly the same issue with ring on a different build system and it turned out the musl wrapper had a different name so I had to override the `CC` environment variable, etc.

**Comment by smw-wagnerma** [comment]
Thanks, you give me the right hint and in combiniation with https://github.com/briansmith/ring/commit/2464e96509eaf45e4172d4c9cdf3fe57a320f032 I solved it. The problem was not the missing musl-gcc, this was installed, it seems that the CC env variable must be set to the clang compiler for the github ubuntu image. My working github action is now:

```
name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-musl --release
        env:
          CC: clang
      - run: |
          zip -r9 -j ./target/x86_64-unknown-linux-musl/release/bootstrap.zip ./target/x86_64-unknown-linux-musl/release/bootstrap
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy to S3 bucket
        run: aws s3 sync ./target/x86_64-unknown-linux-musl/release s3://xxx --delete --exclude="*" --include="bootstrap.zip"
      - name: Update Lambda function
        run: aws lambda update-function-code --function-name "func" --s3-bucket "xxx" --s3-key "bootstrap.zip"

```
And for Cross.toml , I have to passthrough the CC variable:
```

[target.x86_64-unknown-linux-musl]
image = "lambci/lambda:build-provided"

[build.env]
passthrough = [
    "CC",
]
```
Thanks again for your help!
